name: CI

on:
  push:
  pull_request:

jobs:
  build:
    uses: filhype-organization/universal-devops-action/.github/workflows/github-actions.yml@main
    with:
      build_platforms: ['amd64', 'arm64']
      container_build: true
      docker_image_name: 'leeson77/chuck-norris-frontend'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.LOGIN_DOCKER_HUB }}
      DOCKER_TOKEN: ${{ secrets.TOKEN_DOCKER_HUB }}
